<!DOCTYPE html>
<html>
<head>
    <title>ptest html report</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta name="description" content="ptest test results."/>
    <link href="report.css" rel="stylesheet" type="text/css"/>
    <style id="extra-style" type="text/css"></style>
</head>
<body>
<div id="meta">
    Generated by <a href="https://pypi.python.org/pypi/ptest">ptest</a> at 2017-06-05 17:36:26.138141
    <br/><span id="system-info">AndersondeMacBook-Pro.local / Python 3.5.3 / Darwin-16.6.0-x86_64-i386-64bit</span>
</div>
<h1>Test Results</h1>

<div class="main-container">
    <div class="panel navigation">
        <div class="panel-heading">
            <div class="filter-btn all" filter="all">ALL<span class="badge"></span></div>
            <div class="filter-btn passed" filter="passed">PASS<span class="badge"></span></div>
            <div class="filter-btn failed" filter="failed">FAIL<span class="badge"></span></div>
            <div class="filter-btn skipped" filter="skipped">SKIP<span class="badge"></span></div>
        </div>
        <div class="panel-body">
            <div class="toolbar">
                <span class="expand-all">ExpandAll</span>
                <span class="collapse-all">CollapseAll</span>
            </div>
            <div class="tree">
                <ul></ul>
            </div>
        </div>
        <div id="splitter"></div>
    </div>
    <div class="panel detail">
        <div class="panel-heading">
            <span class="text"></span>
        </div>
        <div class="panel-body"></div>
    </div>
</div>
<script type="text/javascript" src="report.js"></script>
<script type="text/javascript">
    // init test suite data
    var testSuite = {"failed": 1, "name": "DefaultSuite", "total": 1, "skipped": 0, "passed": 0, "startTime": "2017-06-05 17:32:23.824374", "fullName": "DefaultSuite", "elapsedTime": 242.309827, "testModules": [{"name": "autotest", "skipped": 0, "passed": 0, "testClasses": [], "fullName": "autotest", "total": 1, "testModules": [{"name": "cases", "skipped": 0, "passed": 0, "testClasses": [], "fullName": "autotest.cases", "total": 1, "testModules": [{"name": "test_login", "skipped": 0, "passed": 0, "testClasses": [{"runGroup": null, "failed": 1, "startTime": "2017-06-05 17:32:23.825130", "elapsedTime": 242.308866, "runMode": "singleline", "endTime": "2017-06-05 17:36:26.133996", "name": "LoginTest", "description": "", "passed": 0, "total": 1, "fullName": "autotest.cases.test_login.LoginTest", "testCases": [{"status": "failed", "beforeMethod": {"screenshots": [], "logs": [], "name": "setup_data", "description": "Prepare test data.", "startTime": "2017-06-05 17:32:23.826666", "fixtureType": "BeforeMethod", "fullName": "autotest.cases.test_login.LoginTest.pass_one_unit@BeforeMethod", "elapsedTime": 9.19954, "status": "passed", "type": "fixture", "endTime": "2017-06-05 17:32:33.026206"}, "startTime": "2017-06-05 17:32:23.826376", "test": {"screenshots": [{"source": "Web&nbsp;Driver", "path": "autotest.cases.test_login.LoginTest.pass_one_unit@Test-1.png"}], "logs": [{"message": "Failed&nbsp;with&nbsp;following&nbsp;message:<br/>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/ptest/testexecutor.py&quot;,&nbsp;line&nbsp;383,&nbsp;in&nbsp;run_test<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.test_fixture.test_fixture_ref.__call__()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/cases/test_login.py&quot;,&nbsp;line&nbsp;36,&nbsp;in&nbsp;pass_one_unit<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.login.pass_one_unit()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/pages/loginpage.py&quot;,&nbsp;line&nbsp;130,&nbsp;in&nbsp;pass_one_unit<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.pass_one_lesson(lessons[i])<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/pages/loginpage.py&quot;,&nbsp;line&nbsp;106,&nbsp;in&nbsp;pass_one_lesson<br/>&nbsp;&nbsp;&nbsp;&nbsp;lesson.click()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py&quot;,&nbsp;line&nbsp;77,&nbsp;in&nbsp;click<br/>&nbsp;&nbsp;&nbsp;&nbsp;self._execute(Command.CLICK_ELEMENT)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py&quot;,&nbsp;line&nbsp;493,&nbsp;in&nbsp;_execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._parent.execute(command,&nbsp;params)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;252,&nbsp;in&nbsp;execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.error_handler.check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/errorhandler.py&quot;,&nbsp;line&nbsp;29,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;wde<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/errorhandler.py&quot;,&nbsp;line&nbsp;24,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;super(MobileErrorHandler,&nbsp;self).check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py&quot;,&nbsp;line&nbsp;194,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;exception_class(message,&nbsp;screen,&nbsp;stacktrace)<br/>selenium.common.exceptions.WebDriverException:&nbsp;Message:&nbsp;An&nbsp;unknown&nbsp;server-side&nbsp;error&nbsp;occurred&nbsp;while&nbsp;processing&nbsp;the&nbsp;command.&nbsp;Original&nbsp;error:&nbsp;UiAUtomator&nbsp;shut&nbsp;down&nbsp;unexpectedly<br/><br/>", "level": "error"}, {"message": "Failed&nbsp;to&nbsp;take&nbsp;the&nbsp;screenshot.<br/>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/ptest/testexecutor.py&quot;,&nbsp;line&nbsp;383,&nbsp;in&nbsp;run_test<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.test_fixture.test_fixture_ref.__call__()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/cases/test_login.py&quot;,&nbsp;line&nbsp;36,&nbsp;in&nbsp;pass_one_unit<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.login.pass_one_unit()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/pages/loginpage.py&quot;,&nbsp;line&nbsp;130,&nbsp;in&nbsp;pass_one_unit<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.pass_one_lesson(lessons[i])<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/pages/loginpage.py&quot;,&nbsp;line&nbsp;106,&nbsp;in&nbsp;pass_one_lesson<br/>&nbsp;&nbsp;&nbsp;&nbsp;lesson.click()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py&quot;,&nbsp;line&nbsp;77,&nbsp;in&nbsp;click<br/>&nbsp;&nbsp;&nbsp;&nbsp;self._execute(Command.CLICK_ELEMENT)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py&quot;,&nbsp;line&nbsp;493,&nbsp;in&nbsp;_execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._parent.execute(command,&nbsp;params)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;252,&nbsp;in&nbsp;execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.error_handler.check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/errorhandler.py&quot;,&nbsp;line&nbsp;29,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;wde<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/errorhandler.py&quot;,&nbsp;line&nbsp;24,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;super(MobileErrorHandler,&nbsp;self).check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py&quot;,&nbsp;line&nbsp;194,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;exception_class(message,&nbsp;screen,&nbsp;stacktrace)<br/>selenium.common.exceptions.WebDriverException:&nbsp;Message:&nbsp;An&nbsp;unknown&nbsp;server-side&nbsp;error&nbsp;occurred&nbsp;while&nbsp;processing&nbsp;the&nbsp;command.&nbsp;Original&nbsp;error:&nbsp;UiAUtomator&nbsp;shut&nbsp;down&nbsp;unexpectedly<br/><br/><br/>During&nbsp;handling&nbsp;of&nbsp;the&nbsp;above&nbsp;exception,&nbsp;another&nbsp;exception&nbsp;occurred:<br/><br/>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/ptest/screencapturer.py&quot;,&nbsp;line&nbsp;337,&nbsp;in&nbsp;take_screenshot<br/>&nbsp;&nbsp;&nbsp;&nbsp;f.write(web_driver.get_screenshot_as_png())<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;863,&nbsp;in&nbsp;get_screenshot_as_png<br/>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;873,&nbsp;in&nbsp;get_screenshot_as_base64<br/>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.execute(Command.SCREENSHOT)['value']<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;252,&nbsp;in&nbsp;execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.error_handler.check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/errorhandler.py&quot;,&nbsp;line&nbsp;29,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;wde<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/errorhandler.py&quot;,&nbsp;line&nbsp;24,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;super(MobileErrorHandler,&nbsp;self).check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py&quot;,&nbsp;line&nbsp;194,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;exception_class(message,&nbsp;screen,&nbsp;stacktrace)<br/>selenium.common.exceptions.WebDriverException:&nbsp;Message:&nbsp;A&nbsp;session&nbsp;is&nbsp;either&nbsp;terminated&nbsp;or&nbsp;not&nbsp;started<br/><br/>", "level": "warning"}], "name": "pass_one_unit", "description": "", "startTime": "2017-06-05 17:32:33.027347", "fixtureType": "Test", "fullName": "autotest.cases.test_login.LoginTest.pass_one_unit@Test", "elapsedTime": 233.102082, "status": "failed", "type": "fixture", "endTime": "2017-06-05 17:36:26.129429"}, "group": "DEFAULT", "elapsedTime": 242.307212, "endTime": "2017-06-05 17:36:26.133588", "name": "pass_one_unit", "description": "", "tags": [], "fullName": "autotest.cases.test_login.LoginTest.pass_one_unit", "afterMethod": {"screenshots": [], "logs": [{"message": "cleaning&nbsp;up", "level": "info"}, {"message": "Failed&nbsp;with&nbsp;following&nbsp;message:<br/>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/ptest/testexecutor.py&quot;,&nbsp;line&nbsp;399,&nbsp;in&nbsp;run_test_configuration<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.test_fixture.test_fixture_ref.__call__()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/cases/test_login.py&quot;,&nbsp;line&nbsp;42,&nbsp;in&nbsp;after<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.login.driver.quit()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;547,&nbsp;in&nbsp;quit<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.execute(Command.QUIT)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;252,&nbsp;in&nbsp;execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.error_handler.check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/errorhandler.py&quot;,&nbsp;line&nbsp;29,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;wde<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/errorhandler.py&quot;,&nbsp;line&nbsp;24,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;super(MobileErrorHandler,&nbsp;self).check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py&quot;,&nbsp;line&nbsp;194,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;exception_class(message,&nbsp;screen,&nbsp;stacktrace)<br/>selenium.common.exceptions.WebDriverException:&nbsp;Message:&nbsp;A&nbsp;session&nbsp;is&nbsp;either&nbsp;terminated&nbsp;or&nbsp;not&nbsp;started<br/><br/>", "level": "error"}, {"message": "The&nbsp;package&nbsp;pyobjc&nbsp;is&nbsp;necessary&nbsp;for&nbsp;taking&nbsp;screenshot&nbsp;of&nbsp;desktop,&nbsp;please&nbsp;install&nbsp;it.", "level": "warning"}], "name": "after", "description": "Clean up", "startTime": "2017-06-05 17:36:26.129607", "fixtureType": "AfterMethod", "fullName": "autotest.cases.test_login.LoginTest.pass_one_unit@AfterMethod", "elapsedTime": 0.003933, "status": "failed", "type": "fixture", "endTime": "2017-06-05 17:36:26.133540"}, "type": "case"}], "skipped": 0, "type": "class"}], "fullName": "autotest.cases.test_login", "total": 1, "testModules": [], "type": "module", "failed": 1}], "type": "module", "failed": 1}], "type": "module", "failed": 1}], "type": "suite", "endTime": "2017-06-05 17:36:26.134201"};
</script>
</body>
</html>